config/routes.rb
Sns::Application.routes.draw do
  devise_for :users

  resources :home
  resources :user_users

  resources :articles
  resources :topics
  resources :users do
    member do
      get 'user_page'
    end
  end

  namespace :admin do
    match "start_super/new",    :controller=>:start_super, :action=>:new
    match "start_super/create", :controller=>:start_super, :action=>:create, :via=>"post"
    match "start_super/destroy",:controller=>:start_super, :action=>:destroy, :via=>"delete"
    resources :users do
      member do
        get 'user_page'
      end
    end
  end

  root :to => 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :title, :summary, :content, :user_id
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :title, :content, :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :confirmable, :lockable

  before_create :confrim   
  def confrim  
    self.confirmed_at = Time.now
  end

  has_many :articles
  has_many :topics

  has_many :user_users
  has_many :users, :through => :user_users, :source => :user

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :phone
  # attr_accessible :title, :body
end

app/models/user_user.rb
class UserUser < ActiveRecord::Base
  # attr_accessible :title, :body

  attr_accessible :user_id, :fan_id, :grade
  belongs_to :user
  belongs_to :fan, class: 'User', foreign_key: 'fan_id'

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def user_page
    @articles = Article.order('id desc').page(params[:page]).per(5)
  end

  def index
  end

  def new
  end

  def create
  end

  def show
    @user = User.find_by_id(params[:id])
    @articles = Article.where(user_id: params[:id]).page(params[:page]).per(20)
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :per_load 

  def index
    if params[:content].blank?
      @articles = Article.order('id desc').page(params[:page]).per(5)
    elsif
      @articles = Article.where("title like ? or summary like ? or content like ? ", "%#{params[:content]}%","%#{params[:content]}%", "%#{params[:content]}%")
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])
    @article.user_id = current_user.id
    if @article.save
      redirect_to :action =>:index
    else
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end
  def update
    if @article.update_attributes(params[:article])
      redirect_to(@article, :notice => 'Article was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private                                                                                                                                      
  def per_load
    @article = Article.find_by_id(params[:id]) if params[:id]
  end 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!

  def index
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_filter :per_load 

  def index
    if params[:content].blank?
      @topics = Topic.order('id desc').page(params[:page]).per(5)
    elsif
      @topics = Topic.where("title like ? or content like ? ", "%#{params[:content]}%", "%#{params[:content]}%")
    end
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(params[:topic])
    if @topic.save
      redirect_to :action =>:index
    else
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end
  def update
    if @topic.update_attributes(params[:topic])
      redirect_to(@topic, :notice => 'Topic was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_path
  end

  private                                                                                                                                      
  def per_load
    @topic = Topic.find_by_id(params[:id]) if params[:id]
  end 

end

app/controllers/user_users_controller.rb
class UserUsersController < ApplicationController
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/user_users_helper.rb
module UserUsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/show.html.erb
<table>                                                                                                                                        
  <tr>
    <th>标题</th> 
    <th>摘要</th> 
    <th>作者</th>
  </tr> 
  <% @articles.each do |article| %>
    <tr>
      <td>
        <%= article.title %>
        <%= link_to '详情',article_path(:id => article.id) %>
      </td>
      <td><%= article.summary %></td>
      <td><%= article.user.name if article.user %></td>
    </tr>
  <% end %>
</table>

app/views/admin/users/user_page.html.erb
<table align="left">
  <thead>
    <tr width="793px">
      <th class="title">标题</th>
      <th class="summary">摘要</th>
      <th class="name">作者</th>
    </tr>
  </thead>

  <tbody> 
    <% @articles.each do |article| %>
      <tr>
        <td align="center">
          <%= link_to article.title, article_path(:id => article.id) %>
        </td>
        <td ><%= article.summary %></td>
        <td align="center"><%= link_to article.user.name, admin_user_path(:id => article.user_id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table align="right"> 
<div> 
  <%= current_user.name %>  
  <%= current_user.email %>  
</div> 
</table> 

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %> 
  <% if @article.errors.any? %>  
    <div id="errorExplanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>  
      <ul>  
        <% @article.errors.full_messages.each do |msg| %>  
          <li><%= msg %></li>  
        <% end %>  
      </ul>  
    </div>  
  <% end %>

  <div class="field">  
    <%= f.label "标题" %><br />  
    <%= f.text_field :title %>  
  </div>

  <div class="field">  
    <%= f.label "摘要" %><br />  
    <%= f.text_area :summary %>  
  </div>

  <div class="field">  
    <%= f.label "内容" %><br />  
    <%= f.ueditor_text :content %>  
  </div>

  <div class="actions">  
    <%= f.submit "提交"%>  
  </div>  
<% end %>  

app/views/articles/edit.html.erb
<h1>Editing article</h1>  
   
<%= render 'form' %>  
   
<%= link_to 'Show', @article %> |   
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
    <table>
      <thead>
        <tr width="793px">
          <th class="title">标题</th> 
          <th class="summary">摘要</th> 
          <th class="name">作者</th>
          <!--th class="count">评论数量</th--> 
          <th class="operate">操作</th> 
        </tr> 
      </thead>
      <tbody>
        <% @articles.each do |article| %>
          <tr>
            <td align="center">
              <%= link_to article.title, article_path(:id => article.id) %>
            </td>
            <td ><%= article.summary %></td>
            <td align="center"><%= article.user.name if article.user %></td>     <!-- if判断是否有用户名-->
            <!--td align="center"><%#= article.comments_number %></td-->
            <td align="center">
              <%= link_to '修改', edit_article_path(:id => article.id), :method => 'get'%>
              <%= link_to '删除', article_path( :id => article.id ), :method => 'delete' %>
            </td>
          </tr>
        <% end %>
      </tbody>
  </table>

  <div class="new"> 
    <%= link_to '新建', new_article_path %>
    <%= link_to '返回主页面',root_path%>
  </div> 
  <%= form_tag articles_path, :method => :get do %> 
    <div class="new"> 
      <%= label_tag "查询关键字" %> 
      <%= text_field_tag :content %>  
      <%= submit_tag "提交" %>
    </div>
  <% end %>

app/views/articles/new.html.erb
<h1>new article</h1>

<%= render 'form' %>

<%= link_to '返回',articles_path %>

app/views/articles/show.html.erb
<p>                                                                                  
<b>标题：</b>
<%= @article.title %>
</p> 

<p>
<b>作者：</b>
<% if @article.user %>
  <%= link_to @article.user.name, user_path(:id => @article.user.id ) %>
<% end %>
</p> 

<p>
<b>摘要：</b>
<%= @article.summary %>
</p>

<p>
<b>内容：</b>
<%= @article.content.html_safe %>
</p> 

<%= link_to '修改',edit_article_path(@article)  %>
<%= link_to '返回文章主页面',articles_path%>
<%= link_to '返回主页面',root_path%> 

app/views/home/index.html.erb
<h1>Welcome To China Football Community</h1>

<%= link_to '文章管理', articles_path%>

<%= link_to '主题管理', topics_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sns</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link href="http://apps.bdimg.com/libs/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <style>
      body {
        padding-top: 50px;
        padding-left: 50px;
      }
    </style>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container-fluid">

      <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">微微微博</a>
        </div>


        <div>
          <div> 
            <ul class="nav navbar-nav">
              <li class="active"><span class="glyphicon glyphicon-home"><%= link_to "首页", user_page_admin_user_path(:id => current_user.id) %>首页</span></li>
              <li><a href="#shop"><span class="glyphicon glyphicon-search">发现</span></a></li>
              <li><a href="#support"><span class="glyphicon glyphicon-user"><%= current_user.name %></span></a></li>
            </ul>
          </div> 
          <div> 
            <ul class="nav navbar-nav">
              <li><a href="#support"><span class="glyphicon glyphicon-wrench"></span></a></li>
              <li><a href="#support"><span class="glyphicon glyphicon-send"></span></a></li>
            </ul>
          </div> 
        </div>

        <div> 
          <form class="form-search">
            <input class="input-medium search-query" type="text" /> <button type="submit" class="btn">查找</button>
          </form>   
        </div> 

      </div>

      <div class="row-fluid">
          <%= yield %>
      </div>

      <div class="row-fluid">
      </div>

    </div>
  </body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %> 
  <% if @topic.errors.any? %>  
    <div id="errorExplanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>  
      <ul>  
        <% @topic.errors.full_messages.each do |msg| %>  
          <li><%= msg %></li>  
        <% end %>  
      </ul>  
    </div>  
  <% end %>

  <div class="field">  
    <%= f.label "标题" %><br />  
    <%= f.text_field :title %>  
  </div>

  <div class="field">  
    <%= f.label "内容" %><br />  
    <%= f.ueditor_text :content %>  
  </div>

  <div class="actions">  
    <%= f.submit "提交"%>  
  </div>  
<% end %> 

app/views/topics/edit.html.erb
<h1>Editing topic</h1>  
   
<%= render 'form' %>  
   
<%= link_to 'Show', @topic %> |   
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<table>
  <thead>
    <tr>
      <th class="title">标题</th> 
      <th class="name">作者</th>
      <th class="operate">操作</th> 
    </tr> 
  </thead>
  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td align="center">
          <%= link_to topic.title, topic_path(:id => topic.id) %>
        </td>
        <td align="center"><%= topic.user.name if topic.user %></td>     <!-- if判断是否有用户名-->
        <td align="center">
          <%= link_to '修改', edit_topic_path(:id => topic.id), :method => 'get'%>
          <%= link_to '删除', topic_path( :id => topic.id ), :method => 'delete' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="new"> 
  <%= link_to '新建', new_topic_path %>
  <%= link_to '返回主页面',root_path%>
</div> 
<%= form_tag topics_path, :method => :get do %> 
  <div class="new"> 
    <%= label_tag "查询关键字" %> 
    <%= text_field_tag :content %>  
    <%= submit_tag "提交" %>
  </div>
<% end %>

app/views/topics/new.html.erb
<h1>new topic</h1>

<%= render 'form' %>

<%= link_to '返回',topics_path %>

app/views/topics/show.html.erb
<p>                                                                                  
<b>标题：</b>
<%= @topic.title %>
</p> 

<p>
<b>作者：</b>
<% if @topic.user %>
  <%= link_to @topic.user.name, user_path(:id => @topic.user.id ) %>
<% end %>
</p> 

<p>
<b>内容：</b>
<%= @topic.content.html_safe %>
</p> 

<%= link_to '修改',edit_topic_path(@topic)  %>
<%= link_to '返回主题主页面',topics_path%>
<%= link_to '返回主页面',root_path%> 